-- ============================================================
-- CREABDPINGU.sql
-- Script de creació de la base de dades del joc Pinguins
-- ============================================================


-- ------------------------------------------------------------
-- SEQUENCIES
-- ------------------------------------------------------------

CREATE SEQUENCE PINGU_PARTIDAS_SEQ
  START WITH 1 INCREMENT BY 1 NOCACHE NOORDER;

CREATE SEQUENCE PINGU_PINGUINOS_SEQ
  START WITH 1 INCREMENT BY 1 NOCACHE NOORDER;

CREATE SEQUENCE PINGU_INVENTARIS_SEQ
  START WITH 1 INCREMENT BY 1 NOCACHE NOORDER;

CREATE SEQUENCE PINGU_EVENTS_SEQ
  START WITH 1 INCREMENT BY 1 NOCACHE NOORDER;


-- ------------------------------------------------------------
-- TAULES
-- ------------------------------------------------------------

CREATE TABLE PINGU_USERS (
  USERNAME          VARCHAR2(50)  PRIMARY KEY,
  PASSWORD          VARCHAR2(100) NOT NULL,
  PARTIDAS_GANADAS  NUMBER        DEFAULT 0,
  PARTIDAS_JUGADAS  NUMBER        DEFAULT 0,
  FECHA_REGISTRO    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PINGU_PARTIDAS (
  ID               NUMBER        PRIMARY KEY,
  USERNAME         VARCHAR2(50)  NOT NULL,
  NOM_PARTIDA      VARCHAR2(100) DEFAULT 'Partida',
  NUM_CASILLAS     NUMBER        NOT NULL,
  CASILLAS_TIPOS   VARCHAR2(4000),
  FOCA_ACTIVADA    NUMBER(1)     DEFAULT 1,
  FOCA_POS         NUMBER        DEFAULT 0,
  FOCA_SOBORNO     NUMBER(1)     DEFAULT 0,
  FOCA_TURNOS_BLOQ NUMBER        DEFAULT 0,
  TURNOS           NUMBER        DEFAULT 0,
  JUGADOR_ACTUAL   NUMBER        DEFAULT 0,
  ACABADA          NUMBER(1)     DEFAULT 0,
  GANADOR          VARCHAR2(50),
  FECHA_GUARDADO   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PINGU_PINGUINOS (
  ID         NUMBER        PRIMARY KEY,
  PARTIDA_ID NUMBER        NOT NULL,
  INDEX_JUG  NUMBER        NOT NULL,
  NOM        VARCHAR2(100) NOT NULL,
  POSICIO    NUMBER        DEFAULT 0
);

CREATE TABLE PINGU_INVENTARIS (
  ID          NUMBER       PRIMARY KEY,
  PINGUINO_ID NUMBER       NOT NULL,
  NOM_ITEM    VARCHAR2(50) NOT NULL,
  QUANTITAT   NUMBER       DEFAULT 0
);

CREATE TABLE PINGU_EVENTS (
  ID         NUMBER        PRIMARY KEY,
  PARTIDA_ID NUMBER        NOT NULL,
  ORDRE      NUMBER        NOT NULL,
  TEXT       VARCHAR2(500) NOT NULL
);


-- ------------------------------------------------------------
-- TRIGGERS
-- ------------------------------------------------------------

CREATE OR REPLACE TRIGGER TRG_PINGU_PARTIDAS_ID
BEFORE INSERT ON PINGU_PARTIDAS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    :NEW.ID := PINGU_PARTIDAS_SEQ.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_INCR_GANADAS
AFTER UPDATE OF ACABADA ON PINGU_PARTIDAS
FOR EACH ROW
WHEN (NEW.ACABADA = 1 AND (OLD.ACABADA IS NULL OR OLD.ACABADA != 1))
BEGIN
  IF :NEW.GANADOR IS NOT NULL THEN
    UPDATE PINGU_USERS
    SET PARTIDAS_GANADAS = PARTIDAS_GANADAS + 1
    WHERE USERNAME = :NEW.GANADOR;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PINGU_SHOW_PCT
AFTER UPDATE OF PARTIDAS_GANADAS ON PINGU_USERS
FOR EACH ROW
WHEN (NEW.PARTIDAS_GANADAS > OLD.PARTIDAS_GANADAS)
DECLARE
  v_pct NUMBER;
BEGIN
  SELECT ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM PINGU_USERS), 1)
  INTO v_pct
  FROM PINGU_USERS
  WHERE PARTIDAS_GANADAS < :NEW.PARTIDAS_GANADAS;
  DBMS_OUTPUT.PUT_LINE('Jugador ' || :NEW.USERNAME ||
    ' te ' || :NEW.PARTIDAS_GANADAS || ' guanyades. ' ||
    v_pct || '% dels jugadors han guanyat menys partides.');
END;
/


-- ------------------------------------------------------------
-- FUNCIONS
-- ------------------------------------------------------------

CREATE OR REPLACE FUNCTION F_PINGU_RECORD RETURN NUMBER IS
  v_max NUMBER;
BEGIN
  SELECT NVL(MAX(PARTIDAS_GANADAS), 0) INTO v_max FROM PINGU_USERS;
  RETURN v_max;
END;
/

CREATE OR REPLACE FUNCTION F_PINGU_MITJA RETURN NUMBER IS
  v_avg NUMBER;
BEGIN
  SELECT ROUND(NVL(AVG(PARTIDAS_GANADAS), 0), 2) INTO v_avg FROM PINGU_USERS;
  RETURN v_avg;
END;
/

CREATE OR REPLACE FUNCTION F_PINGU_PCT_MENYS(p_wins IN NUMBER) RETURN NUMBER IS
  v_total NUMBER;
  v_menys NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_total FROM PINGU_USERS;
  IF v_total = 0 THEN RETURN 0; END IF;
  SELECT COUNT(*) INTO v_menys FROM PINGU_USERS WHERE PARTIDAS_GANADAS < p_wins;
  RETURN ROUND(v_menys * 100.0 / v_total, 1);
END;
/


-- ------------------------------------------------------------
-- PROCEDIMENTS
-- ------------------------------------------------------------

CREATE OR REPLACE PROCEDURE P_PINGU_JUGADORS_RECORD(
  p_record IN NUMBER,
  p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_cursor FOR
    SELECT USERNAME, PARTIDAS_GANADAS
    FROM PINGU_USERS
    WHERE PARTIDAS_GANADAS = p_record
    ORDER BY USERNAME;
END;
/

CREATE OR REPLACE PROCEDURE P_PINGU_SOBRE_MITJA(
  p_cursor OUT SYS_REFCURSOR
) AS
  v_mitja NUMBER;
BEGIN
  SELECT AVG(PARTIDAS_GANADAS) INTO v_mitja FROM PINGU_USERS;
  OPEN p_cursor FOR
    SELECT USERNAME, PARTIDAS_GANADAS
    FROM PINGU_USERS
    WHERE PARTIDAS_GANADAS > v_mitja
    ORDER BY PARTIDAS_GANADAS DESC;
END;
/

CREATE OR REPLACE PROCEDURE P_PINGU_RANKING(
  p_username IN VARCHAR2,
  p_cursor   OUT SYS_REFCURSOR
) AS
  v_count   NUMBER;
  v_partidas NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM PINGU_USERS WHERE USERNAME = p_username;
  IF v_count = 0 THEN
    RAISE_APPLICATION_ERROR(-20001, 'Jugador ' || p_username || ' no existeix.');
  END IF;
  SELECT COUNT(*) INTO v_partidas FROM PINGU_PARTIDAS WHERE USERNAME = p_username;
  IF v_partidas = 0 THEN
    RAISE_APPLICATION_ERROR(-20002, 'El jugador ' || p_username || ' no ha guardat cap partida.');
  END IF;
  OPEN p_cursor FOR
    SELECT USERNAME, PARTIDAS_GANADAS, PARTIDAS_JUGADAS,
           CASE WHEN PARTIDAS_JUGADAS > 0
                THEN ROUND(PARTIDAS_GANADAS * 100.0 / PARTIDAS_JUGADAS, 1)
                ELSE 0 END AS RATIO
    FROM PINGU_USERS
    ORDER BY PARTIDAS_JUGADAS DESC, PARTIDAS_GANADAS DESC;
END;
/
